/* Resource Datei Indizes fÅr VIEWER1 */

#define MMENU            0   /* Menuebaum */
#define MMENU_ACC        3   /* TITLE in Baum MMENU */
#define MMENU_FILE       4   /* TITLE in Baum MMENU */
#define MMENU_EDIT       5   /* TITLE in Baum MMENU */
#define MMENU_ABOUT      8   /* STRING in Baum MMENU */
#define MMENU_OPEN       17  /* STRING in Baum MMENU */
#define MMENU_CLOSE      18  /* STRING in Baum MMENU */
#define MMENU_QUIT       20  /* STRING in Baum MMENU */
#define MMENU_SETTINGS   22  /* STRING in Baum MMENU */

#define SETTINGS         1   /* Formular/Dialog */
#define SETTINGS_FONT1   3   /* BOXTEXT in Baum SETTINGS */
#define SETTINGS_FONT2   4   /* BOXTEXT in Baum SETTINGS */
#define SETTINGS_FONT3   5   /* BOXTEXT in Baum SETTINGS */
#define SETTINGS_FONT4   6   /* BOXTEXT in Baum SETTINGS */
#define SETTINGS_FONT5   7   /* BOXTEXT in Baum SETTINGS */
#define SETTINGS_FONT6   8   /* BOXTEXT in Baum SETTINGS */
#define SETTINGS_FONT7   9   /* BOXTEXT in Baum SETTINGS */
#define SETTINGS_FONT8   10  /* BOXTEXT in Baum SETTINGS */
#define SETTINGS_FONT9   11  /* BOXTEXT in Baum SETTINGS */
#define SETTINGS_FONT10  12  /* BOXTEXT in Baum SETTINGS */
#define SETTINGS_UPARROW 13  /* BOXCHAR in Baum SETTINGS */
#define SETTINGS_SLIDBAR 14  /* BOX in Baum SETTINGS */
#define SETTINGS_SLIDER  15  /* BOX in Baum SETTINGS */
#define SETTINGS_DOWNARR 16  /* BOXCHAR in Baum SETTINGS */

#define FILEERR          0   /* Alert String */
