name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: Install packages
      run: |
        sudo add-apt-repository ppa:vriviere/ppa && sudo apt-get update
        sudo apt-get install cross-mint-essential dos2unix hatari aranym mtools lftp
    
    - name: install libcmini
      run: |
        cd ..
        mkdir libcmini
        wget -q -O - https://github.com/freemint/libcmini/archive/master.tar.gz | tar xzf - --strip-components=1 -C libcmini
        cd libcmini
        make
    
    - name: install gemlib
      run: |
        cd ..
        mkdir gemlib
        wget -q -O - https://github.com/freemint/gemlib/archive/master.tar.gz | tar xzf -
        cd gemlib-master
        sudo make install -j
        
    - name: Display package versions
      run: |
        git --version
        make --version
        ld --version
        gcc --version
        awk -W version
        m68k-atari-mint-ld --version
        m68k-atari-mint-ar --version
        m68k-atari-mint-gcc --version
        tar --version
        unix2dos --version
        lftp --version
        hatari --version || true
        aranym --version
        
    - name: Build binaries
      run: |
        make clean
        make all
      
