name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: Install packages
      run: |
        sudo add-apt-repository ppa:vriviere/ppa && sudo apt-get update
        sudo apt-get install cross-mint-essential dos2unix hatari aranym mtools lftp
    - name: Display package versions
      run: |
        git --version
        make --version
        ld --version
        gcc --version
        awk -W version
        m68k-atari-mint-ld --version
        m68k-atari-mint-ar --version
        m68k-atari-mint-gcc --version
        tar --version
        unix2dos --version
        lftp --version
        hatari --version || true
        aranym --version
    - name: Build binaries
      run: |
        make clean
        make all
      
